ALTER TABLE "Settings" ADD COLUMN "salaMode" TEXT NOT NULL DEFAULT 'off';
ALTER TABLE "Settings" ADD COLUMN "salaFixo" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Settings" ADD COLUMN "salaPct" REAL NOT NULL DEFAULT 0;
